### ISSUE TITLE
Need a help mechanism that works for folks in the room & virtually! 

### ISSUE THREAD

**Issue by JosephMcArthur** [sparcopen/open-research-doathon#11]

**Comment by Daniel-Mietchen** [comment]
Joe had mentioned 
https://github.com/ehzhang/HELPq
as potentially useful here.

**Comment by JosephMcArthur** [comment]
We could have a hangout running constantly & have them answer key Q's. We could set up a slack type channel for the weekend too perhaps?

**Comment by Daniel-Mietchen** [comment]
I think it's simpler to have someone in the room who actively monitors and posts to
[#odd4r](https://twitter.com/search?vertical=default&q=odd4r), ideally with links to replies to any questions that pop up.

**Comment by npscience** [comment]
At a recent hackathon (200 people, 10-20 mentors):
+ HelpQ was fine except you had to constantly be watching the queue, and it is set up for a mentor-participant type arrangement.
+ Slack worked best: posting in specific channels, and calling certain people for help
+ what about an IRC? like gitter? freenode?
+ I guess for openness, twitter might be best? Can we draw up an easy list of twitter handles to enable people to chat directly with each other?

**Comment by JosephMcArthur** [comment]
* using hangouts during idea pitches / lightening talks
* I'll monitor odd4r
