### ISSUE TITLE
Link up with other Open Data Day activities

### ISSUE THREAD

**Issue by Daniel-Mietchen** [sparcopen/open-research-doathon#12]
As per http://opendataday.org/
and also things like http://brainhack.org/brainhack-global-2017/ .

**Comment by Daniel-Mietchen** [comment]
I asked the open data day list for coordination around topics, e.g. research: https://groups.google.com/forum/#!topic/open-data-day/ukgb74zaGcw .

I also tweeted an invite for such interactions: https://twitter.com/EvoMRI/status/833645164824506369 .

We should probably think of doing more like that.

**Comment by npscience** [comment]
Max Ogden and Danielle Robinson are also running an event: Data Rescue Portland https://www.eventbrite.com/e/open-data-day-portland-tickets-31370043645
It's about adding good metadata to make research data more findable. Seems relevant to add to the .readme, and we could suggest people contribute virtually?

**Comment by Daniel-Mietchen** [comment]
Thanks - added: https://github.com/sparcopen/open-research-doathon/commit/efe7bec9abf3a90d32f40d28eba20b283d72a6b1 .
