### ISSUE TITLE
Provide mechanism to match contributor interests with project needs

### ISSUE THREAD

**Issue by Daniel-Mietchen** [sparcopen/open-research-doathon#15]
Some attendees might come with ideas about what they'd like to do (e.g. something like "work on UX"), explore (e.g. "statistical irregularities in the reporting of clinical trials") or learn (e.g. "[D3](https://d3js.org/)").

Projects, on the other hand, typically have relatively specific needs where there is room for different ways to go about addressing them. They might also have room for expanding into different areas ("now we need some use cases"), which provides room to accommodate different interests.

We should have a mechanism (beyond the idea pitches) to match the needs and interests of the projects and attendees.

This is closely related to but different from #14.

**Comment by JosephMcArthur** [comment]
Post its? We could have a quick session where folks in the room stick up all their skills on a board maybe?

**Comment by Daniel-Mietchen** [comment]
I think there should be some pre-filtering &mdash; "all their skills" is just too much.
Also, why not use GitHub issues instead of post-its?

Perhaps we should be looking into something like
- experience
  - hackathon experience  
    - if yes, then provide a sentence about it
    - if no, then express your expectations
  - open data activities
  - open source experience
- main skills
  - programming
    - which languages? name up to three
  - databases
    - which? name up to three
  - visualization/ sonification
    - which libraries? name up to three
  - technical documentation
  - user experience
  - anything else

Perhaps we can use labels here to organize that? I just created one for "skills" that could be used to tag such posts (should we have one for "experience" as well?), and we could have additional tags for the skills listed above.

**Comment by Daniel-Mietchen** [comment]
For on-site participants, there could also be a way to use the name tags (#24) for this purpose.

**Comment by edsaperia** [comment]
Is this just for this event? Or for events in general? Or a general solution to this issue in all contexts?

I encounter this issue regularly and would be happy to work on designing a solution.

**Comment by Daniel-Mietchen** [comment]
@edsaperia 
We initially had this ticket only for this event, and I just came in to close it now that we have #42. But yes, it is a frequent problem, so perhaps open a new idea issue for it and give a pitch on it?

**Comment by JosephMcArthur** [comment]
For small groups, this sort of does itself. However, the intro doc really helped - simply control f for what you need!
