### ISSUE TITLE
Add code of conduct

### ISSUE THREAD

**Issue by Daniel-Mietchen** [sparcopen/open-research-doathon#17]
As per https://help.github.com/articles/adding-a-code-of-conduct-to-your-project/

**Comment by JosephMcArthur** [comment]
I suggest the opencon code of conduct: www.opencon2016.org/code_of_conduct. Only as I know it well and can enforce it.

**Comment by Daniel-Mietchen** [comment]
That's good but a bit long and also CC BY.

**Comment by Daniel-Mietchen** [comment]
A basic version of a code of conduct is now available via
https://github.com/sparcopen/open-research-doathon/blob/master/CONTRIBUTING.md#conduct .
