### ISSUE TITLE
Document suitably themed ideas posted elsewhere

### ISSUE THREAD

**Issue by Daniel-Mietchen** [sparcopen/open-research-doathon#18]
Many research-related projects have public issue trackers. Some even use more explicit mechanisms to invite contributions, e.g. the [Need Contributor](https://github.com/scikit-learn/scikit-learn/labels/Need%20Contributor) and [Sprint](https://github.com/scikit-learn/scikit-learn/labels/Sprint) labels over at https://github.com/scikit-learn/scikit-learn .

It would be useful for this doathon and similar events later on if we could find a mechanism to match those existing ideas with event participants who do not have a specific idea to work on.

**Comment by Daniel-Mietchen** [comment]
Another source of ideas is https://github.com/mozillascience/global-sprint-2016/issues .

**Comment by JosephMcArthur** [comment]
Have these made it into the readme?
