### ISSUE TITLE
Designing introduction for the event

### ISSUE THREAD

**Issue by JosephMcArthur** [sparcopen/open-research-doathon#19]
[//]: # "=======================
Guidelines for contributing: 
(1) Write your post below using Markdown (as per https://guides.github.com/features/mastering-markdown/ ) or just plain text
(2) Add the appropriate label (e.g. 'idea' or 'lightning talk', or both for idea pitches) to your post - use 'help wanted' as needed
(3) Don't worry about these introductory lines - you can leave or delete them, as they won't display anyway (you can check this via Preview)
(4) Hit the 'Submit new issue' button
============================"

### Current plan

* Daniel & I speak for as short a time as possible
* Peer to peer start. Split folks into groups of 5-8 to speak about
  * who they are
  * why they came
  * what they know about open data (and making sure folks are at the same-ish) level
* have a facilitator for each group. Facilitator makes notes & a tweet about everyone. 
* break into pitches after (get folks up by github tag)

**Comment by Daniel-Mietchen** [comment]
In terms of the who/ why/ what, I think we can use
- https://github.com/sparcopen/open-research-doathon/labels/skills
- https://github.com/sparcopen/open-research-doathon/labels/interests
- https://github.com/sparcopen/open-research-doathon/labels/experience .

If that's fine with you, I can add it to the issue template.

**Comment by JosephMcArthur** [comment]
Need to:
* do housekeeping (toilets, fire exits, wifi)
* flag any issues with food provided
* see if folks don't want to be photographed

**Comment by JosephMcArthur** [comment]
* please do on twitter / github
* fine to move groups
* documentation 30 seconds
* theme around "do-a-thon"
* intro groups to : https://docs.google.com/document/d/1gTdPPr0ZMCKv5X-_XL9au6buwV6Fz194djjw3YXSFvs/edit#

**Comment by JosephMcArthur** [comment]
* mention that there are going to be pitches. Put them on github
* hand raising (out of 28 people in the room)
  * what's your background ( 6 research | 2 librarian | 6 student | 9 advocate | 5 public / wildcard )
  * how many of you are experienced around research data? 11
  * how many of you have not been to a hack / do-a-thon before? 7
  * how many of you come from outside of london? 10
  * how many of you have made open data before? 3
  * how many of you are dependant on open data? 6
* who doesn't know anyone here? 11

**Comment by JosephMcArthur** [comment]
* ask folks about dietary needs & talk about food
