### ISSUE TITLE
Set up issue and contributor templates

### ISSUE THREAD

**Issue by Daniel-Mietchen** [sparcopen/open-research-doathon#2]
As described in
https://help.github.com/articles/setting-guidelines-for-repository-contributors/
and
https://github.com/blog/2111-issue-and-pull-request-templates

**Comment by Daniel-Mietchen** [comment]
A reasonable issue template now sits at
https://github.com/sparcopen/open-research-doathon/blob/master/ISSUE_TEMPLATE.md .

Lots of contributor templates to be found at
https://github.com/search?utf8=%E2%9C%93&q=CONTRIBUTING.md ,
some really good like
https://github.com/scikit-learn/scikit-learn/blob/master/CONTRIBUTING.md
and some under CC0 like
https://github.com/jsdnxx/CONTRIBUTING.md . I'm still looking for the intersection of both.

**Comment by JosephMcArthur** [comment]
Looks great!

**Comment by Daniel-Mietchen** [comment]
A basic version of the contributor template is now up at
https://github.com/sparcopen/open-research-doathon/blob/master/CONTRIBUTING.md .

Closing.
