### ISSUE TITLE
Nail down food / drink provision for both days

### ISSUE THREAD

**Issue by JosephMcArthur** [sparcopen/open-research-doathon#20]
[//]: # "=======================
Guidelines for contributing: 
(1) Write your post below using Markdown (as per https://guides.github.com/features/mastering-markdown/ ) or just plain text
(2) Add the appropriate label (e.g. 'idea' or 'lightning talk', or both for idea pitches) to your post - use 'help wanted' as needed
(3) Don't worry about these introductory lines - you can leave or delete them, as they won't display anyway (you can check this via Preview)
(4) Hit the 'Submit new issue' button
============================"

**Comment by Daniel-Mietchen** [comment]
This should be mentioned in the introduction (#19).

**Comment by JosephMcArthur** [comment]
Okay, hot drinks can be provided by Nwspk, and be self serve. I can pick up a wide variety of other cold drinks the day before. They can be stored in the fridge at the event. 

For food, I'd suggest easy to eat food for lunch. I can pick up a variety of bagels nearby easily, and add some fruit / snacks etc to add variety. Where folks have super specific needs (I'll cater for the obvious) we can handle that on the day. 

For breakfast, we can do croissants / yoghurts etc generally a selection breakfasty food :) 

Generally, I can have things prepped that will deal with 95% of needs here beforehand, and on the day we'll just need to deal with special needs & perhaps respond to feedback.

**Comment by JosephMcArthur** [comment]
Closing for now, but, if you have feedback let me know.
