### ISSUE TITLE
Supply a list of resources to test out reproducible computational tools

### ISSUE THREAD

**Issue by Daniel-Mietchen** [sparcopen/open-research-doathon#21]
[//]: # "=======================
Guidelines for contributing: 
(1) Write your post below using Markdown (as per https://guides.github.com/features/mastering-markdown/ ) or just plain text
(2) Add the appropriate label (e.g. 'idea' or 'lightning talk', or both for idea pitches) to your post - use 'help wanted' as needed
(3) Don't worry about these introductory lines - you can leave or delete them, as they won't display anyway (you can check this via Preview)
(4) Hit the 'Submit new issue' button
============================"
In
https://github.com/sparcopen/open-research-doathon/blob/master/README.md ,
it is stated
"Test out reproducible computational tools such as Binder, R-Shiny, CodeOcean [we can supply a list of resources]". We should probably provide that list ahead of time.

**Comment by npscience** [comment]
I'm developing that list today. What's the best format to provide it as?

**Comment by Daniel-Mietchen** [comment]
perhaps a markdown file that we can put into this repo.

**Comment by npscience** [comment]
FYI - just updated that .md file, it's ready to commit now. I'll be OOO until the weekend, but will be responsive if you need anything else.

**Comment by Daniel-Mietchen** [comment]
Please do commit it - we can't see it here yet.

**Comment by Daniel-Mietchen** [comment]
Ah, OK, just saw (and merged) the pull request.

Closing.
