### ISSUE TITLE
Name tags

### ISSUE THREAD

**Issue by Daniel-Mietchen** [sparcopen/open-research-doathon#24]
[//]: # "=======================
Instructions for posting issues: 
(1) Write your post below using Markdown (as per https://guides.github.com/features/mastering-markdown/ ) or just plain text.
(2) Add the appropriate labels to your post, e.g. 'idea' or 'lightning talk' (or both for idea pitches), 'interests', 'skills' or 'experience'. Use 'help wanted' as needed.
(3) Don't worry about these introductory lines - you can leave or delete them, as they won't display anyway (you can check this via Preview).
(4) Hit the 'Submit new issue' button.
============================"

We should have some way of identifying on-site participants to each other. I'm using "name tags" here as a shorthand and am open to other ways of doing this.

**Comment by JosephMcArthur** [comment]
So, we can certainly have actual name tags! As a start ;)

**Comment by JosephMcArthur** [comment]
going to do intro's via the gdoc & tweet
