### ISSUE TITLE
Provide WiFi access to on-site participants

### ISSUE THREAD

**Issue by Daniel-Mietchen** [sparcopen/open-research-doathon#29]
[//]: # "=======================
Instructions for posting issues: 
(1) Write your post below using Markdown (as per https://guides.github.com/features/mastering-markdown/ ) or just plain text.
(2) Add the appropriate labels to your post, e.g. 'idea' or 'lightning talk' (or both for idea pitches), 'interests', 'skills' or 'experience'. Use 'help wanted' as needed.
(3) Don't worry about these introductory lines - you can leave or delete them, as they won't display anyway (you can check this via Preview).
(4) Hit the 'Submit new issue' button.
============================"

I think that was already sorted out - just making sure.

**Comment by JosephMcArthur** [comment]
All over it!
