### ISSUE TITLE
Think about illustrations

### ISSUE THREAD

**Issue by Daniel-Mietchen** [sparcopen/open-research-doathon#3]
In useful amounts and with a clear link to the hackathon theme, illustrations, sonifications and similar can help to engage with the relevant communities.

**Comment by JosephMcArthur** [comment]
on it!

**Comment by Daniel-Mietchen** [comment]
@JosephMcArthur Can you upload your files somewhere, e.g. Wikimedia Commons?

**Comment by Daniel-Mietchen** [comment]
Here are some other images that may be of use (should all be CC0/PD):
- https://commons.wikimedia.org/wiki/File%3ASandbox_with_interactive_projection_at_31c3.jpg
- https://commons.wikimedia.org/wiki/File%3AThe-global-distribution-of-the-arbovirus-vectors-Aedes-aegypti-and-Ae.-albopictus-elife08347fs004.jpg
- https://commons.wikimedia.org/wiki/File%3AComposition_ruins_Pompeii.jpg
- https://commons.wikimedia.org/wiki/File%3AMonnaie_de_Bactriane%2C_Eucratide_I%2C_face.jpg
- https://commons.wikimedia.org/wiki/File%3AIonic_solution_measure.jpg
- https://commons.wikimedia.org/wiki/File%3ATethys_enhanced_color.jpeg
- https://commons.wikimedia.org/wiki/File%3APaderborn-Landeshospital_Grabungen-6.jpg
- https://commons.wikimedia.org/wiki/File%3ABrachiosaurus_brancai%2C_Tendaguru%2C_Tanzania_-_Museum_fur_Naturkunde%2C_Berlin_-_DSC00053.JPG
- https://commons.wikimedia.org/wiki/File%3AZuunSalaaTomb.jpg
- https://commons.wikimedia.org/wiki/File:Pahoeoe_fountain_edit2.jpg
- https://commons.wikimedia.org/wiki/File:Iss030e015472_Edit.jpg
- https://commons.wikimedia.org/wiki/File:Antarctica_6400px_from_Blue_Marble.jpg
- https://commons.wikimedia.org/wiki/File:Pluto-01_Stern_03_Pluto_Color_TXT.jpg
- https://commons.wikimedia.org/wiki/File:Coiled_Galaxy.jpg
- https://commons.wikimedia.org/wiki/File:Heart3D.png
- https://commons.wikimedia.org/wiki/File:Ultraviolet_image_of_the_Cygnus_Loop_Nebula_crop.jpg
- any of the images in https://en.wikisource.org/wiki/Wikisource:WikiProject_Open_Access/Programmatic_import_from_PubMed_Central/Cenozoic_Planktonic_Marine_Diatom_Diversity_and_Correlation_to_Climate_Change
- https://www.flickr.com/photos/usoceangov/16824332958/
- https://www.flickr.com/photos/joshuatreenp/17116004370/
- https://www.flickr.com/photos/internetarchivebookimages/18238456119/
- https://www.flickr.com/photos/noaasatellites/31789432354/
- https://www.flickr.com/photos/internetarchivebookimages/14748371154/
- https://www.flickr.com/photos/britishlibrary/11291366414/
- https://www.flickr.com/photos/internetarchivebookimages/14587230758/
- https://www.flickr.com/photos/internetarchivebookimages/14770108311/
- https://www.flickr.com/photos/usoceangov/17011150541/
- https://www.flickr.com/photos/usoceangov/16783590887/
- https://www.flickr.com/photos/usoceangov/16370816963/
- https://www.flickr.com/photos/usoceangov/16803267158/

Some of them have already been included in the README.

I explicitly did not look for images like
- https://www.flickr.com/photos/jimkaskade/15504424016/ , which are often used in such contexts.

**Comment by JosephMcArthur** [comment]
Looks like there are lots of great images we can use here! Closing to keep things tidy but please reopen if desired.
