### ISSUE TITLE
Create a tool to measure which newspaper uses the most words from newspeak in their online articles.

### ISSUE THREAD

**Issue by andrea-f** [sparcopen/open-research-doathon#30]
[//]: # "=======================
Instructions for posting issues: 
(1) Write your post below using Markdown (as per https://guides.github.com/features/mastering-markdown/ ) or just plain text.
(2) Add the appropriate labels to your post, e.g. 'idea' or 'lightning talk' (or both for idea pitches), 'interests', 'skills' or 'experience'. Use 'help wanted' as needed.
(3) Don't worry about these introductory lines - you can leave or delete them, as they won't display anyway (you can check this via Preview).
(4) Hit the 'Submit new issue' button.
============================"

It would be interesting to create a tool that analyses newspaper articles published in their online edition and gives an estimate on how much newspeak words (from 1984) are used. Provide a ranking of these newspapers and host the tool publicly so it can be shared and a mechanism (cron jobs?) so the information stays up to date.

See you tomorrow,
Andrea

**Comment by Daniel-Mietchen** [comment]
Some background on Newspeak vocabulary: https://en.wikipedia.org/wiki/List_of_Newspeak_words .

**Comment by andrea-f** [comment]
Thanks Daniel, noted ;)

**Comment by andrea-f** [comment]
Coding with @AndreaCrotti https://github.com/andrea-f/newspeak/

**Comment by edsaperia** [comment]
I recommend chatting to https://twitter.com/sophches, who is doing relevant research in this area.

**Comment by Daniel-Mietchen** [comment]
@andrea-f You showed a prototype yesterday - can you post the link here?

**Comment by nicklakasas** [comment]
We will be closing the ticket soon, but this doesn't mean it cannot be worked on.
Only some housekeeping from the event.

**Comment by andrea-f** [comment]
Hi @Daniel-Mietchen the screenshot used is in the git repo.

**Comment by Daniel-Mietchen** [comment]
Ah, OK - hadn't noticed [it](http://i.imgur.com/isbzXS7.png) was a screenshot.
