### ISSUE TITLE
Create a catalogue of what's wrong with the current research system

### ISSUE THREAD

**Issue by Daniel-Mietchen** [sparcopen/open-research-doathon#32]
Lots of problems with the research system are being discussed in different places, and progress in identifying or addressing them is hard to monitor.

To address that, it would be useful to have a mechanism to keep track of individual issues. I'd like to prototype such a mechanism and have set up a "[bug reports to science](https://github.com/br2s/bug-reports-to-science/)" repo for that purpose, where issues with the research system could be [posted](https://github.com/br2s/bug-reports-to-science/issues) just like bug reports at normal GitHub repos.

**Comment by npscience** [comment]
I think this is a really interesting project. I wonder if it would be useful to start by:
(i) adding some headings for the major issues
(ii) these could define an input field for people to start contributing key resources about the issue, and/or key steps for solving the problem via a form interface (for non-githubbers)

**Comment by npscience** [comment]
Perhaps this list of Q&As might help to start us off: https://openscience.uni-bielefeld.de/ @Daniel-Mietchen

**Comment by npscience** [comment]
and this: http://ec.europa.eu/research/openscience/index.cfm?pg=home&section=monitor

**Comment by Daniel-Mietchen** [comment]
@npscience yes, the Open Science Q & A site is related in spirit, but "bug reports to science" is broader, as the lack of openness is not the only problem around. I expect both sites to cross-fertilize where they overlap, though.
For some first ideas of what I think would fit better to the bug reports approach, see the issues I have posted there so far: https://github.com/br2s/bug-reports-to-science/issues .

As for the Open Science Monitor, see my comment at https://twitter.com/EvoMRI/status/844209560088952835 .
