### ISSUE TITLE
Zotero plugin for Literature Discovery using Open Citation Data

### ISSUE THREAD

**Issue by barney-walker** [sparcopen/open-research-doathon#33]
[//]: # "=======================
Instructions for posting issues: 
(1) Write your post (below this text blob) using Markdown (as per https://guides.github.com/features/mastering-markdown/ ) or just plain text.
(2) Add the appropriate labels to your post, e.g. 'idea' or 'lightning talk' (or both for idea pitches), 'interests', 'skills' or 'experience'. Use 'help wanted' as needed.
(3) Don't worry about these introductory lines - you can leave or delete them, as they won't display anyway (you can check this via Preview).
(4) Hit the 'Submit new issue' button.
============================"

Citations represent something fundamental about the flow of knowledge and ideas in science. However, our current tools for making use of this information in day-to-day research are extremely limited.

I've been working on a tool to allow researchers to build localised citation networks from a small group of 'seed papers' that define a particular area of interest and use these networks to discover highly relevant papers in that area.

For more information see the github repository [here](https://github.com/bjw49/CitationExplorer/blob/master/README.md) or an interactive demo using a static data-set [here](https://bwalker.shinyapps.io/citationtool2/).

Currently, the demo is populated with data downloaded manually from the Web of Science and coded in RShiny. I'd like help developing the tool to automatically acquire data using the [Open Citation Corpus](http://opencitations.net/) API and rewriting it in JavaScript (D3) for more flexibility and ultimate integration with the Open-Source literature management software Zotero.

**Comment by fionabradley** [comment]
does Google (boo) Scholar have citation data that can be reused also for this kind of project?

**Comment by Daniel-Mietchen** [comment]
@bjw49 Have you looked into using Wikidata as a backend, e.g. as in [Scholia](https://tools.wmflabs.org/scholia/)?

**Comment by npscience** [comment]
Take a look at https://github.com/knowledge-direct/knowledge-direct for some efforts to start this.

**Comment by JosephMcArthur** [comment]
Take a look at: openknowledgemaps.org

**Comment by fionabradley** [comment]
https://core.ac.uk/ has a 'similar' articles feature but don't believe it is doing this from citations, would be great to add this feature there.

**Comment by markdurrant** [comment]
Repo here ==> https://github.com/markdurrant/open-research-hack-citation-explorer

**Comment by barney-walker** [comment]
Microsoft Academic API seems promising as a data source.
