### ISSUE TITLE
Newbies guide to Wikidata

### ISSUE THREAD

**Issue by ekoner** [sparcopen/open-research-doathon#35]
A session to introduce anyone new to [Wikidata](https://www.wikidata.org/wiki/Wikidata:Main_Page): What it is, how to use it, current projects and potential uses.

**Comment by goodwingibbins** [comment]
How do I check if certain data is up yet? Take this for example, one of the most central climate observation data sets.

https://www.esrl.noaa.gov/gmd/ccgg/trends/

**Comment by Daniel-Mietchen** [comment]
@goodwingibbins 

1. check whether a Wikidata item exists to which such data might fit, e.g. [atmosphere of Earth (Q3230)](https://www.wikidata.org/wiki/Q3230) or [Mauna Loa (Q159762)](https://www.wikidata.org/wiki/Q159762). If it does not, then consider creating a suitable item by way of https://www.wikidata.org/wiki/Special:NewItem
1. check whether a suitable Wikidata property exists for this data type by going through https://www.wikidata.org/wiki/Special:ListProperties or https://www.wikidata.org/wiki/Template:Chemical_compound_properties or related listings. If you don't find any, consider proposing such a property via https://www.wikidata.org/wiki/Wikidata:Property_proposals .

To get an idea as to whether creating such new items or properties would be appropriate, take a look at related items and properties or ask at the talk page of one of the relevant [WikiProjects](https://www.wikidata.org/wiki/Category:WikiProjects) or at the [project chat](https://www.wikidata.org/wiki/Wikidata:Project_chat)

**Comment by Daniel-Mietchen** [comment]
The observations of the group that looked into this are now available via
https://github.com/sparcopen/open-research-doathon/blob/master/wikidata_for_newbies.md .

**Comment by Daniel-Mietchen** [comment]
I notified the Wikidata mailing list about this: https://lists.wikimedia.org/pipermail/wikidata/2017-March/010379.html .

**Comment by wetneb** [comment]
I've made a diagram to explain how "instance of" (P31) and "subclass of" (P279) work together:

![Explanation](https://tools.wmflabs.org/openrefine-wikidata/static/explanation_types_wikidata.svg)

https://tools.wmflabs.org/openrefine-wikidata/static/explanation_types_wikidata.svg

**Comment by Daniel-Mietchen** [comment]
I've added this team's issue to the [discussion](https://phabricator.wikimedia.org/T159216) about an upcoming Wikidata documentation sprint.

**Comment by Daniel-Mietchen** [comment]
Just noticed that the video of Edafe's pitch has not been listed here yet, so here's a quick fix: https://twitter.com/OKFN/status/838011416598700033 .

**Comment by Daniel-Mietchen** [comment]
Wikidata now has https://www.wikidata.org/wiki/Wikidata:WikiProject_Welcome .
