### ISSUE TITLE
R interface to anthropology database D-Place

### ISSUE THREAD

**Issue by matthewgthomas** [sparcopen/open-research-doathon#36]
[//]: # "=======================
Instructions for posting issues: 
(1) Write your post (below this text blob) using Markdown (as per https://guides.github.com/features/mastering-markdown/ ) or just plain text.
(2) Add the appropriate labels to your post, e.g. 'idea' or 'lightning talk' (or both for idea pitches), 'interests', 'skills' or 'experience'. Use 'help wanted' as needed.
(3) Don't worry about these introductory lines - you can leave or delete them, as they won't display anyway (you can check this via Preview).
(4) Hit the 'Submit new issue' button.
============================"
[D-Place](https://d-place.org) is an open online database of places, languages, cultures/societies and environments. The idea is to create an R interface for querying this database so researchers and others can fit statistical models / visualise the data (or whatever else they'd like to do). I reckon there are two potential routes:

1. Take advantage of D-Place's RESTful API, similar to the [europepmc R package](https://github.com/ropensci/europepmc)
2. Write a workflow for people to download the data (which is in [its own repository](https://github.com/D-PLACE/dplace-data)) and do relevant pre-processing (D-Place's [loading script is here](https://github.com/NESCent/dplace/blob/master/load_all_datasets.sh)) so they have their own local copy

**Comment by Daniel-Mietchen** [comment]
@matthewgthomas Do you want to give a pitch on this? If so, would be good if you could record a video/webcast of yourself explaining the matter, and upload that to YouTube or so. If that sounds too complicated, we can try to set up a Hangout or such. Ping @JosephMcArthur if you need help with that.

**Comment by matthewgthomas** [comment]
I've uploaded a short webcast pitch here: https://youtu.be/UMR7N193uM8 (will also Twit the link)

**Comment by matthewgthomas** [comment]
I managed to put together a bare-bones R package: https://github.com/matthewgthomas/rdplace
Only one function at the moment, but more to come...

**Comment by Daniel-Mietchen** [comment]
Great!

**Comment by npscience** [comment]
@matthewgthomas Hiya, we're closing issues right now, because it's the end of the event. Great to see your work so far! We'd love it if you continue to post in here or at least link to any ongoing work.

**Comment by matthewgthomas** [comment]
@npscience Hi, I've been doing a bit more work on this package: https://github.com/matthewgthomas/dplacer
