### ISSUE TITLE
Visualization of trade between the UK and Europe

### ISSUE THREAD

**Issue by ahussain3** [sparcopen/open-research-doathon#39]
[//]: # "=======================
Instructions for posting issues: 
(1) Write your post (below this text blob) using Markdown (as per https://guides.github.com/features/mastering-markdown/ ) or just plain text.
(2) Add the appropriate labels to your post, e.g. 'idea' or 'lightning talk' (or both for idea pitches), 'interests', 'skills' or 'experience'. Use 'help wanted' as needed.
(3) Don't worry about these introductory lines - you can leave or delete them, as they won't display anyway (you can check this via Preview).
(4) Hit the 'Submit new issue' button.
============================"

Seems like it could be cool. There must be enough data out there.

**Comment by pherterich** [comment]
Which tool did you demo again for storytelling with data? Didn't have the chance to take notes during your pitch. Thanks!

**Comment by ahussain3** [comment]
We have a data source for this!
http://atlas.media.mit.edu/en/resources/data/

@pherterich - the site was http://polygraph.cool
