### ISSUE TITLE
Reach out to relevant communities about the event

### ISSUE THREAD

**Issue by Daniel-Mietchen** [sparcopen/open-research-doathon#4]
e.g. open science mailing list, openscience and opendata hashtags and similar.
Use the [#odd4r](https://twitter.com/hashtag/odd4r?f=tweets) hashtag by default.

**Comment by npscience** [comment]
I've emailed c. 170 ECRs with London, Oxford or Cambridge email addresses in the eLife system; to date, 8 have clicked through to the Eventbrite page.

As discussed with Joe, on my list to email today are:
[x] Academy of Medical Sciences
[x] Society for Experimental Biology - Sarah Blackford
[x] OpenConCam (includes Cambridge Open Data team)
[x] GRASP, the Cambridge PhD and postdoc society

Update: contacted the above.

**Comment by Daniel-Mietchen** [comment]
Great - thanks!

**Comment by barney-walker** [comment]
I've managed to get an email sent around the Physics and Bioengineering departments at Imperial College London.  I've also posted on the Science Disrupt Slack and got a mention in their Weekly Memo.

EDIT: also sent an email around the Open Research London mailing list.
