### ISSUE TITLE
Climate Visualisations

### ISSUE THREAD

**Issue by goodwingibbins** [sparcopen/open-research-doathon#40]
[//]: # "=======================
Instructions for posting issues: 
(1) Write your post (below this text blob) using Markdown (as per https://guides.github.com/features/mastering-markdown/ ) or just plain text.
(2) Add the appropriate labels to your post, e.g. 'idea' or 'lightning talk' (or both for idea pitches), 'interests', 'skills' or 'experience'. Use 'help wanted' as needed.
(3) Don't worry about these introductory lines - you can leave or delete them, as they won't display anyway (you can check this via Preview).
(4) Hit the 'Submit new issue' button.
============================"

We want to avoid the push and pull of whether or not to "trust" scientists. Loads of the historical data around climate science is freely available (https://www.esrl.noaa.gov/gmd/ccgg/trends/) but not somewhere pretty I can point people to, where they can understand the process and conclusions, without getting into programming themselves.

How?

**Comment by goodwingibbins** [comment]
This is probably best achieved by working on #26 first! Anyway, it's a use-case I'm particularly interested in.

**Comment by nicklakasas** [comment]
Here is what I did to join some data together.

1. Found some raw data - http://www.wri.org/resources/data-sets/cait-historical-emissions-data-countries-us-states-unfccc
2. Uploaded this into open refine. Download me from http://openrefine.org/
3. You can then link data from wikidata based on the open refine data. Below is an example expression I used. It joins the Country column from the open refine dataset to the wikidata country property. Then it shows the currency of the country. Click on the drop down arrow on the column, choose edit columns, add column by fetching URLs... 
`"https://tools.wmflabs.org/openrefine-wikidata/fetch_values?prop=P38&flat=true&item="+cells["Country"].recon.match.id`

This concept could be quite useful to find correlations between high emissions and a particular country property.
