### ISSUE TITLE
The ideas that I might help do something about

### ISSUE THREAD

**Issue by Daniel-Mietchen** [sparcopen/open-research-doathon#42]
OK, so this is a test post to see whether we could use such issues to see who 
- is interested in 
- could contribute to
any of the ideas posted.

So here we go:
I posted issues #25 #32 #34 . I am also interested in #31 and I could probably help with #33 and #35.

**Comment by kshamash** [comment]
I'm working on #34 Sonify ongoing research. Any JavaScript experts available to help?

**Comment by JosephMcArthur** [comment]
I'm interested in #41, #34, #26

**Comment by npscience** [comment]
I posted #28 #26 
I'm working on #28 this afternoon; and interested to chat through #26 with any contributors
I would like to help with #41 #34 #25 #38 #6, perhaps tomorrow
I'm on table one

**Comment by mrw34** [comment]
I'm most interested in #25 but also would be happy to help with #31. Unfortunately I'm only around today though. I'm on table 3!

**Comment by rfinean** [comment]
I'm interested in #41, #6, #26 and #28 for medical physiological research data

**Comment by petermr** [comment]
Interested in #31 and #35 
in #31 a general question of who can / should edit #wikidata and when. 

- Can you push any set of triples?
- must every triple be checked?
- is a set of triples too "uninteresting" ?
- how do we update #wikidata when the basic authority changes (e.g. update of public dictionary)?

**Comment by petermr** [comment]
What are the uses cases for #wikidata? #31 and #35

- identifying / disambiguating an object A in a document
- linking one object A to another B
- determining the relationship between A and B
- semantic queries - what A have properties X, Y at time T?
- finding reference data for an object - the gestation period of an Okapi is 14.5 +- 0.5 months
- aggregating common types of data ("all UK libraries")
- time dependence of a property (population of country X)

**Comment by gpa-smith** [comment]
I'm interested in #26 (- table 1 at the moment), #37, #28 and can potentially help with all of these and #41

**Comment by VsGab** [comment]
I'm interested in #33, #38 and #28 (brainstorming part). On table 5 (gabriel) at the moment

**Comment by matthewgthomas** [comment]
I'm interested in #26, #33 and #46 (especially keen to help on #46 beyond this event)
