### ISSUE TITLE
If you need help, then please post in this thread.

### ISSUE THREAD

**Issue by Daniel-Mietchen** [sparcopen/open-research-doathon#43]
While feeling your way into a project, you might identify certain skills or other forms of expertise (domain knowledge, front-end etc.) that your team might need help with. For example, #34 would benefit from some JavaScript expertise, as per https://github.com/sparcopen/open-research-doathon/issues/42#issuecomment-284151466 .

Please post such cases here so that we can keep track of them.

**Comment by gpa-smith** [comment]
Not specifically technical expertise, but if any researchers can offer insight into how unstructured metadata is generated, stored and managed during the research process this could help to assess the level of metadata for final published datasets  #26

**Comment by Daniel-Mietchen** [comment]
We could use help with filling [the spreadsheet](https://docs.google.com/spreadsheets/d/1txg0u9zARHrLkY4MYuz5vmsVCZUOItgybEHqx13Bkbc/edit#gid=0) we're using for tracking progress on #25:

1. checking the paper for mentions of "Jupyter" or "ipynb", with the idea to enter into column AD either the URL of the notebook or "n/a" if there is none (e.g. "Jupyter" is only mentioned in general terms, not in reference to a specific notebook)
1. re-running those notebooks and documenting your observations in the columns AE and AF.

The first task can be done by anyone, the latter requires some experience with Python and / or Jupyter.

**Comment by nicklakasas** [comment]
I'll help with this one.

**Comment by barney-walker** [comment]
If anyone who knows python wants to help me play around with the [google scholar scraper](https://github.com/lecy/google-scholar-scraper-in-python) let me know!

Also still looking for people to help on the JavaScript side.
