### ISSUE TITLE
Things learned

### ISSUE THREAD

**Issue by Daniel-Mietchen** [sparcopen/open-research-doathon#45]
Whenever you learn something during the course of this event, make a note in this thread.

For instance, I learned that GitHub labels cannot be used by anyone posting an issue, which affects some of the plans we had for using them. Overview:
https://github.com/sparcopen/open-research-doathon/labels .

This is loosely related to #16.

**Comment by edsaperia** [comment]
https://hypothes.is/ allows you to annotate anything online. It has social features, unique public identifiers, and is open source.

**Comment by DanSanz** [comment]
http://vega.github.io/ open source visualisation

**Comment by nicklakasas** [comment]
http://openrefine.org/ <-- I've been using to upload data from a flat file and then link that data set to [wikidata](https://www.wikidata.org/).

**Comment by barney-walker** [comment]
Making SPARQL queries to [opencitations.net](opencitations.netl)

**Comment by HKLondon** [comment]
Some of the links to BMJ Open's [pages about data management](http://bmjopen.bmj.com/pages/datamanagement/) are broken. (Have asked Publisher to update links)

**Comment by nicklakasas** [comment]
You can update wikidata not only directly, but via a game type system as well. Have a look http://tools.wmflabs.org/wikidata-game and make it better!

**Comment by JosephMcArthur** [comment]
We can sonify our work!

**Comment by Daniel-Mietchen** [comment]
Joe's comment above is referring to #52.

**Comment by Daniel-Mietchen** [comment]
There's a lot to be learned about author disambiguation by going to 
https://orcid.org/orcid-search/quick-search?searchQuery=%22Li+Li%22
and clicking "Show more" for a while.

**Comment by Daniel-Mietchen** [comment]
There is a lot to be learned about how to make Jupyter notebooks reproducible:
https://markwoodbridge.com/2017/03/05/jupyter-reproducible-science.html .
