### ISSUE TITLE
Open charity impact data

### ISSUE THREAD

**Issue by SanjayRedScarf** [sparcopen/open-research-doathon#46]
[//]: # "=======================
Instructions for posting issues: 
(1) Write your post (below this text blob) using Markdown (as per https://guides.github.com/features/mastering-markdown/ ) or just plain text.
(2) Add the appropriate labels to your post, e.g. 'idea' or 'lightning talk' (or both for idea pitches), 'interests', 'skills' or 'experience'. Use 'help wanted' as needed.
(3) Don't worry about these introductory lines - you can leave or delete them, as they won't display anyway (you can check this via Preview).
(4) Hit the 'Submit new issue' button.
============================"

Charities have information / data about their "impact" - the good they do in the world. It is currently scattered in various different reports - mostly the charity's annual report.

I am working on putting this data into a database and have made a start - some results here:
http://thinkingaboutcharity.blogspot.co.uk/2016/09/most-charities-are-not-cost-effective_21.html

I'm also working on making this data available/useful to people.

Would be good to think of ways to input the data in a scalable way.  Some of it is scrapable, but the most important data I've been gathering by reading through the reports and identifying the relevant numbers/information.

**Comment by fionabradley** [comment]
I had a chat with your colleague about this really interesting idea... a couple of thoughts based on past experience:

I agree with you that overheads are not a good measure of effectiveness. They are absolutely necessary to effectiveness in many cases to ensure that a charity can actually implement and steward the funds they receive.
[Charity Navigator](https://www.charitynavigator.org/) and other sites do a good job of evaluating charity effectiveness overall and have a trusted model. [Foundation Center](http://foundationcenter.org/) is also a good resource.

In terms of impact, it really depends who impact is defined for. In many cases, it's not for the donor, but the audience is their major funders or regulators or board members. So in terms of methodology it's important to consider impact evaluation in that context - for instance a possible impact might be described as: as a result of our intervention (whether that's capacity building, infrastructure, technology whatever), we were able to get better funding for a service/better health outcomes for one person. Cost per intervention may or may not be important, or reach may or may be important - but sometimes a really good outcome can be achieved by few. It depends. I think [Camfed's reporting](https://camfed.org/our-impact/) is very effective for instance for the type of impact that reaches individuals. Policy reform type impact is reported differently.

You may like to look at some of the work going on around the [data revolution](https://www.google.co.uk/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwi9y8zMlb3SAhVMDcAKHS_LDbUQFggcMAA&url=http%3A%2F%2Fwww.undatarevolution.org%2Fwp-content%2Fuploads%2F2014%2F11%2FA-World-That-Counts.pdf&usg=AFQjCNFQhGCgu9Eq_17JsFhWMNh-a_fh1Q) to see where some of the big thinking about data in development is going, and keeping an eye on the [SGD16 data platform](http://www.sdg16.org/) and talk to people in [Bond](https://www.bond.org.uk/).

**Comment by ag1000** [comment]
I would be interested in helping (member of DataKind UK) :)

**Comment by wetneb** [comment]
I'm interested too! And happy to upload stuff to Wikidata :-)

**Comment by C21Beancounter** [comment]
1) Peer Group Support (economists): http://www.probonoeconomics.com/ (help charities improve understanding on their impact);
2) Tech for good support: http://www.datakind.org/chapters/datakind-uk (currently promoting "Data Maturity in Charities).

**Comment by Daniel-Mietchen** [comment]
Not sure this is helpful here but 
https://opencorporates.com/
may be worth a look, as it gathers data about companies in a way that could be relevant for charities, though not necessarily in terms of impact.

**Comment by C21Beancounter** [comment]
Sorry forgot to add.  As discussed, the "Effective Altruism"/Give Well in the Charity arena might be the equivalent of "Net Positive" approach (to Climate Change) in the business world.  https://www.forumforthefuture.org/blog/net-positive-principles (quick ref to 12 principles) and https://www.theclimategroup.org/news/net-positive (for the full report).

**Comment by Daniel-Mietchen** [comment]
I think some organizations to test-drive such "open charity impact data" workflow might be
- http://okfn.org/
- https://wikimedia.org.uk/
- https://science.mozilla.org/ (not sure about their legal status of a charity)
- http://wellcome.ac.uk/

**Comment by C21Beancounter** [comment]
Me again:
1) When it comes round again consider applying for ODI startups accelerator: http://theodi.org/news/four-new-open-data-startups-join-odi-startup-accelerator-programme

2) Will get back to you about Charity Reporting /XBRL.  Not sure how much the SoRP expects impact data to be reported (my understanding is it is Financial information only), but here is some background: https://xbrl.frc.org.uk/  AND https://www.xbrl.org/news/uk-authorities-to-collect-financial-data-from-charities-in-xbrl/ .  

3) CICs report on their impact but unfortunately that is unlikely to be structured (as there isnt a hard core"standard" governing what they need to report, let alone a machine-readable format of their impact reporting): https://www.gov.uk/government/publications/form-cic34-community-interest-company-report.
