### ISSUE TITLE
Recognise contributors to the projects using a hat rack

### ISSUE THREAD

**Issue by npscience** [sparcopen/open-research-doathon#49]
[//]: # "=======================
Instructions for posting issues: 
(1) Write your post (below this text blob) using Markdown (as per https://guides.github.com/features/mastering-markdown/ ) or just plain text.
(2) Add the appropriate labels to your post, e.g. 'idea' or 'lightning talk' (or both for idea pitches), 'interests', 'skills' or 'experience'. Use 'help wanted' as needed.
(3) Don't worry about these introductory lines - you can leave or delete them, as they won't display anyway (you can check this via Preview).
(4) Hit the 'Submit new issue' button.
============================"
Not all github contributions are code commits. A hatrack reveals all the contributions, which is particularly useful for an event based on commenting on issues. See https://github.com/LABHR/hatrack.

**Comment by JosephMcArthur** [comment]
Just did it! https://labhr.github.io/hatrack/#repo=sparcopen/open-research-doathon

**Comment by JosephMcArthur** [comment]
Webpage made: https://sparcopen.github.io/open-research-doathon/Let's%20Build%20a%20Hat%20Rack.html

**Comment by npscience** [comment]
Updated link: [https://josephmcarthur.github.io/do-a-thon_hatrack/Let's%20Build%20a%20Hat%20Rack.html](https://josephmcarthur.github.io/do-a-thon_hatrack/Let's%20Build%20a%20Hat%20Rack.html)
