### ISSUE TITLE
OpenRefine+Wikidata quick demo

### ISSUE THREAD

**Issue by wetneb** [sparcopen/open-research-doathon#5]
I have been working on a tool that sounds quite relevant for the event:

https://tools.wmflabs.org/openrefine-wikidata/

It helps align datasets to Wikidata in OpenRefine, a super cool software to deal with messy data. If you  are still looking for lightning talks during the event, I would be happy to give a quick demo of the tool. I'd love it if we could then play with the tool on some research data (and I'm sure some attendees will know of many interesting datasets).

**Comment by Daniel-Mietchen** [comment]
Yes, your reconciliation tool looks great and would be a good thing to demo, play with and hack on. We haven't fully figured out how to organize the lightning talks, other than the generic slot for them in the program. We'll update that as things become more concrete.

**Comment by Daniel-Mietchen** [comment]
I just gave this a try.

I downloaded the results of [this SPARQL query](https://query.wikidata.org/#%23Find%20common%20strings%20for%20authors%20of%20scientific%20articles%0ASELECT%20%2a%20WHERE%20%7B%0A%20%20%7B%0A%20%20%20%20SELECT%20%3Fauthorstring%20%28COUNT%28%3Fpaper%29%20AS%20%3Fcount%29%20WHERE%20%7B%20%7B%20%3Fpaper%20wdt%3AP2093%20%3Fauthorstring%20.%20%7D%7D%0A%20%20%20%20GROUP%20BY%20%3Fauthorstring%0A%20%20%7D%0A%0A%20%20%20FILTER%28%3Fcount%20%3E%2030%29%0A%7D)

```
#Find common strings for authors of scientific articles
SELECT * WHERE {
  {
    SELECT ?authorstring (COUNT(?paper) AS ?count) WHERE { { ?paper wdt:P2093 ?authorstring . }}
    GROUP BY ?authorstring
  }

   FILTER(?count > 30)
}
```

and [fed them into OpenRefine](http://127.0.0.1:3333/project?project=2285090869390), which resulted in 351 matching rows that I then converted to the format of the [new author resolver](https://tools.wmflabs.org/sourcemd/new_resolve_authors.php?), which gave [this list](https://www.wikidata.org/w/index.php?title=User:Daniel_Mietchen/sandbox&oldid=445704775), from where I then picked cases to look at in more detail, which resulted in ca. 1k [replacements](https://www.wikidata.org/w/index.php?title=Q28740367&type=revision&diff=445702033&oldid=445680146) of P2093 statements with the corresponding P50 statements. That looks promising.

Things that still need attention in this workflow:
- The transitions [from SPARQL to Open Refine](https://github.com/wetneb/openrefine-wikidata/issues/7) and from there to the author resolver are currently manual, and some information gets lost along the way. For instance, Open Refine comes up with a good set of potential matches between the P2093 text strings from the query and item labels of instances of Q5 but the author resolver is not aware of these potential matches and basically repeats the same search (though it struggles with periods in names).

Pinging @magnusmanske


I also tried to tackle another problem by way of a similar pipeline:
* [SPARQL query](https://query.wikidata.org/#%23%20scientific%20journal%20%28Q5633421%29%20as%20main%20subject%20%28P921%29%0ASELECT%20%3Fitem%20%3Ftopic%20%3FtopicLabel%20WHERE%20%7B%0A%20%20%3Fitem%20wdt%3AP921%20%3Ftopic%20.%0A%20%20%3Ftopic%20wdt%3AP31%20wd%3AQ5633421%20.%20%0A%20%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22en%22.%20%7D%0A%7D%0AORDER%20BY%20%3Ftopic)
```
# scientific journal (Q5633421) as main subject (P921)
SELECT ?item ?topic ?topicLabel WHERE {
  ?item wdt:P921 ?topic .
  ?topic wdt:P31 wd:Q5633421 . 
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en". }
}
ORDER BY ?topic
```
* [Results in Open Refine](http://127.0.0.1:3333/project?project=1661218071827)

This is where I got stuck. Can the tool be used at all in any way that would help with replacing those journal items in P921 statements with the corresponding items about the actual topics, as per the mapping [here](https://www.wikidata.org/w/index.php?title=User:Daniel_Mietchen&oldid=445636268#Journals_as_main_subject)?

**Comment by wetneb** [comment]
@Daniel-Mietchen Thanks for giving it a spin! But your links to OpenRefine refer to your local instance of the tool, that we cannot access. Screenshots?

Concerning your mapping, I have some ideas to make this work if the mapping is stored on Wikidata (as journal to topic statements). I'll add the relevant endpoint and make screenshots to explain how to use it.

**Comment by Daniel-Mietchen** [comment]
This was my first try with Open Refine, so I'm still trying to find my way around. Is there no way to make my OpenRefine projects open, perhaps even by default? Would be nice to have them synced with Zenodo or so for every "release".

In this specific case, though, I don't think it matters too much (and screenshots wouldn't make much of a difference), since I simply took the outputs of both SPARQL queries (in csv format) and imported them into OpenRefine.

**Comment by Daniel-Mietchen** [comment]
Re lightning talks, we now have #13 to get them organized.

**Comment by ekoner** [comment]
+1

**Comment by kshamash** [comment]
Very cool! I'm testing it out on this dataset https://figshare.com/articles/COAF_Jisc_and_RCUK_APC_data_2013-2015/3462620

**Comment by wetneb** [comment]
So, we've done a lot of things on this topic:
- [x] demonstrating Wikidata and OpenRefine to many participants
- [x] trying the reconciliation service on various datasets
- [x] fixing bugs in the reconciliation interface, https://github.com/wetneb/openrefine-wikidata/commit/d2176d3e47d8b577d785f40e9be67b4e4deab84d https://github.com/wetneb/openrefine-wikidata/commit/48e2ac63c2d725610e8ce2e7f2ec70d9800b36dd https://github.com/wetneb/openrefine-wikidata/commit/93c11eac5364653e4943703fdc0444aa1353bb43
- [x] better documentation for the reconciliation, with pictures: https://github.com/OpenRefine/OpenRefine/wiki/Reconciliation

So many thanks to all who got involved!
