### ISSUE TITLE
Test whether we can hear GitHub activity in this repo

### ISSUE THREAD

**Issue by Daniel-Mietchen** [sparcopen/open-research-doathon#52]
as per the "GitHub Audio" mentioned in #34 (which we are running right now), we should hear it when I am posting this issue.

**Comment by JosephMcArthur** [comment]
testing a comment!

**Comment by Daniel-Mietchen** [comment]
It works - we just heard it.

**Comment by Daniel-Mietchen** [comment]
To be precise, we heard the original posting - and the closing - of the issue but not the comments.
