### ISSUE TITLE
Find step by step resources for authors that help them make their data open

### ISSUE THREAD

**Issue by JosephMcArthur** [sparcopen/open-research-doathon#6]

**Comment by npscience** [comment]
From Max Ogden and Danielle Robinson: step 1 is metadata, step 2 is archiving. No point in step 2 without step 1. They may write up this reasoning.

**Comment by rfinean** [comment]
[Open Data Handbook](http://opendatahandbook.org/guide/en/how-to-open-up-data/) is a good starting point. [Frictionless Data](http://frictionlessdata.io/guides/publish/tabular/) has tools and guides for adding metadata and packaging.
